### ISSUE TITLE
 Fatal error: Call to undefined function CommerceGuys\Intl\Formatter\bccomp() in /var/platform/www/vendor/commerceguys/intl/src/Formatter/NumberFormatter.php on line 164

### ISSUE THREAD

**Issue by yograf** [mglaman/platform-docker#52]
On product/add/default
any ideas?

**Comment by mglaman** [comment]
@yograf the php-fpm container needs bcmath. I'll make a commit

**Comment by mglaman** [comment]
:( shoot it is there; can you verify your Dockerfile has

```
&& docker-php-ext-install mcrypt pdo_mysql mysql mysqli mbstring opcache soap bcmath \
```

https://github.com/mglaman/platform-docker/blob/develop/resources/images/php/Dockerfile#L10

**Comment by yograf** [comment]
@mglaman thanks Matt. That was the problem.
bcmath  is missing on v. 1.0.7 which composer installed.

**Comment by mglaman** [comment]
Thanks, @yograf for heads up. I tagged a new minor
